### ISSUE TITLE
[Feature] Documentation on adding content from 3DMM expansions to 3DMMF?

### ISSUE THREAD

**Issue by wertercatt** [foone/3DMMForever#15]
The tagged release mentions that adding content from Nickelodeon 3D Movie Maker (and presumably ドラえもんキャラクターキット as well) 'can't be done easily.' Ideally, documentation should be added to walk users through the process of adding this content.

**Comment by foone** [comment]
That's a good idea. Generally the answer is twofold:
1. It's not yet documented because it's not easy to use it that way. You technically can, but you shouldn't, really. It'll be made easier later. 
2. The best option for if you want a full install is still to use the original disc (or the ISO), following [the guide on 3dmm.com ](https://3dmm.com/showthread.php?t=17038). 

2 is probably the best way to go, honestly. until v3dmm is updated it won't work at all with this current release of 3dmmForever, so... you can only mostly make it work.

**Comment by frank-weindel** [comment]
Opened #39 to address the expansions issue. Closing this.
